-- TABELA: FINAI_PAYMENT_METHOD
CREATE TABLE FINAI_PAYMENT_METHOD (
    payment_method_id NUMBER PRIMARY KEY,
    payment_method_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- TABELA: FINAI_CATEGORY
CREATE TABLE FINAI_CATEGORY (
    category_id NUMBER PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL,
    category_description VARCHAR2(255)
);

-- TABELA: FINAI_RECURRING
CREATE TABLE FINAI_RECURRING (
    recurring_id NUMBER PRIMARY KEY,
    name VARCHAR2(20) NOT NULL
);

-- TABELA: FINAI_MOVEMENT_TYPE
CREATE TABLE FINAI_MOVEMENT_TYPE (
    movement_type_id NUMBER PRIMARY KEY,
    movement_name VARCHAR2(50) NOT NULL,
    movement_type_description VARCHAR2(255)
);

-- TABELA: FINAI_MOVEMENT
CREATE TABLE FINAI_MOVEMENT (
    movement_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    payment_method_id NUMBER NOT NULL,
    movement_type_id NUMBER NOT NULL,
    value NUMBER(10, 2) NOT NULL,
    description VARCHAR2(255),
    movement_date DATE NOT NULL,
    recurring_id NUMBER NOT NULL,

    -- FOREIGN KEYS
    CONSTRAINT fk_finai_movement_category
        FOREIGN KEY (category_id) REFERENCES FINAI_CATEGORY (category_id),
    CONSTRAINT fk_finai_movement_payment_method
        FOREIGN KEY (payment_method_id) REFERENCES FINAI_PAYMENT_METHOD (payment_method_id),
    CONSTRAINT fk_finai_movement_type
        FOREIGN KEY (movement_type_id) REFERENCES FINAI_MOVEMENT_TYPE (movement_type_id),
    CONSTRAINT fk_finai_movement_recurring
        FOREIGN KEY (recurring_id) REFERENCES FINAI_RECURRING (recurring_id),
    CONSTRAINT fk_finai_movement_user
        FOREIGN KEY (user_id) REFERENCES FINAI_USERS (id)
);
